optimized, improve lsp, improve file explorer, aesthetic pleasing

diff --git a/dev-env b/dev-env
--- a/dev-env
+++ b/dev-env
@@ -31,7 +31,10 @@ update_files() {
     local src="$1"
     local dest="$2"
     log "Copying directories from $src to $dest"
-    pushd "$src" >/dev/null || { echo "Cannot change directory to $src" >&2; return 1; }
+    pushd "$src" >/dev/null || {
+        echo "Cannot change directory to $src" >&2
+        return 1
+    }
     while IFS= read -r -d '' dir; do
         local base_dir="${dir#./}"
         local target="${dest%/}/$base_dir"
diff --git a/init b/init
--- a/init
+++ b/init
@@ -7,14 +7,19 @@ git submodule init
 git submodule update
 
 echo "Checking out 'main' branch in env/.config/nvim..."
-pushd env/.config/nvim >/dev/null || { echo "Failed to change directory to env/.config/nvim" >&2; exit 1; }
+pushd env/.config/nvim >/dev/null || {
+    echo "Failed to change directory to env/.config/nvim" >&2
+    exit 1
+}
 git checkout main
 popd >/dev/null
 
 echo "Checking out 'master' branch in tmux-sessionizer..."
-pushd tmux-sessionizer >/dev/null || { echo "Failed to change directory to tmux-sessionizer" >&2; exit 1; }
+pushd tmux-sessionizer >/dev/null || {
+    echo "Failed to change directory to tmux-sessionizer" >&2
+    exit 1
+}
 git checkout master
 popd >/dev/null
 
 echo "Init script completed."
-
diff --git a/luarocks-3.11.1/publishrelease b/luarocks-3.11.1/publishrelease
--- a/luarocks-3.11.1/publishrelease
+++ b/luarocks-3.11.1/publishrelease
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
 
 [ "$1" ] || {
-   echo "usage.....: $0 <version>"
-   echo "example...: $0 3.1.1"
-   echo
-   echo "Before running this, make sure the packages were built:"
-   echo "   makedist 3.1.1 /opt/lua54/ binary sign"
-   echo "And the tag was merged:"
-   echo "   mergerelease 3.1.1"
-   echo
-   exit 1
+    echo "usage.....: $0 <version>"
+    echo "example...: $0 3.1.1"
+    echo
+    echo "Before running this, make sure the packages were built:"
+    echo "   makedist 3.1.1 /opt/lua54/ binary sign"
+    echo "And the tag was merged:"
+    echo "   mergerelease 3.1.1"
+    echo
+    exit 1
 }
 
 #######################################
@@ -19,28 +19,27 @@
 v="$1"
 
 git checkout v$v || {
-   echo "Could not checkout release tag."
+    echo "Could not checkout release tag."
 }
 
 packages=(
-   luarocks-$v-windows-32.zip
-   luarocks-$v-windows-32.zip.asc
-   luarocks-$v-windows-64.zip
-   luarocks-$v-windows-64.zip.asc
-   luarocks-$v-linux-x86_64.zip
-   luarocks-$v-linux-x86_64.zip.asc
-   luarocks-$v-win32.zip
-   luarocks-$v-win32.zip.asc
-   luarocks-$v.tar.gz
-   luarocks-$v.tar.gz.asc
+    luarocks-$v-windows-32.zip
+    luarocks-$v-windows-32.zip.asc
+    luarocks-$v-windows-64.zip
+    luarocks-$v-windows-64.zip.asc
+    luarocks-$v-linux-x86_64.zip
+    luarocks-$v-linux-x86_64.zip.asc
+    luarocks-$v-win32.zip
+    luarocks-$v-win32.zip.asc
+    luarocks-$v.tar.gz
+    luarocks-$v.tar.gz.asc
 )
 
-for f in "${packages[@]}" luarocks-$v-1.rockspec
-do
-   [ -e "$f" ] || {
-      echo "Missing file $f"
-      exit 1
-   }
+for f in "${packages[@]}" luarocks-$v-1.rockspec; do
+    [ -e "$f" ] || {
+        echo "Missing file $f"
+        exit 1
+    }
 done
 
 #######################################
@@ -48,24 +47,23 @@ done
 #######################################
 
 function confirm() {
-   branch="$1"
+    branch="$1"
 
-   echo "****************************************"
-   git diff $branch
-   echo "****************************************"
-   git status
-   echo "****************************************"
+    echo "****************************************"
+    git diff $branch
+    echo "****************************************"
+    git status
+    echo "****************************************"
 
-   echo "Everything looks all right? (y/n)"
-   echo "(Answering y will commit and push)"
-   read
-   if ! [ "$REPLY" == "y" ]
-   then
-      git reset
-      git checkout .
-      git checkout master
-      exit 1
-   fi
+    echo "Everything looks all right? (y/n)"
+    echo "(Answering y will commit and push)"
+    read
+    if ! [ "$REPLY" == "y" ]; then
+        git reset
+        git checkout .
+        git checkout master
+        exit 1
+    fi
 }
 
 #######################################
@@ -103,7 +101,7 @@ gawk '
       print
    }
 }
-' index.html > index.html.1
+' index.html >index.html.1
 mv index.html.1 index.html
 git add index.html
 
@@ -124,7 +122,7 @@ gawk '
       print "}},"
    }
 }
-' releases.json > releases.json.1
+' releases.json >releases.json.1
 mv releases.json.1 releases.json
 git add releases.json
 
@@ -147,14 +145,13 @@ git checkout master
 # luarocks-site
 #######################################
 
-if [ -e ../luarocks-site ]
-then
-   cd ../luarocks-site
-   git pull
+if [ -e ../luarocks-site ]; then
+    cd ../luarocks-site
+    git pull
 else
-   cd ..
-   git clone ssh://git@github.com/luarocks/luarocks-site
-   cd luarocks-site
+    cd ..
+    git clone ssh://git@github.com/luarocks/luarocks-site
+    cd luarocks-site
 fi
 
 sed -i 's,luarocks-[0-9]*\.[0-9]*\.[0-9]*,luarocks-'$v',' static/md/home.md
@@ -170,18 +167,17 @@ git push
 #######################################
 
 [ -e ../luarocks.wiki ] || {
-   cd ..
-   git clone ssh://git@github.com/luarocks/luarocks.wiki.git
+    cd ..
+    git clone ssh://git@github.com/luarocks/luarocks.wiki.git
 }
 
-if [ -e ../luarocks.wiki ]
-then
-   cd ../luarocks.wiki
-   git pull
+if [ -e ../luarocks.wiki ]; then
+    cd ../luarocks.wiki
+    git pull
 else
-   cd ..
-   git clone ssh://git@github.com/luarocks/luarocks.wiki.git
-   cd luarocks.wiki
+    cd ..
+    git clone ssh://git@github.com/luarocks/luarocks.wiki.git
+    cd luarocks.wiki
 fi
 
 sed -i "s,Latest release: .*,Latest release: '''LuaRocks $v''' - '$(date +'%d/%b/%Y')'," Download.mediawiki
@@ -200,7 +196,7 @@ BEGIN {
 // {
    print
 }
-' "Release-history.mediawiki" > "Release-history.mediawiki.1"
+' "Release-history.mediawiki" >"Release-history.mediawiki.1"
 mv "Release-history.mediawiki.1" "Release-history.mediawiki"
 
 git add "Download.mediawiki"
diff --git a/resources/luarocks b/resources/luarocks
--- a/resources/luarocks
+++ b/resources/luarocks
@@ -15,7 +15,10 @@ echo "Extracting LuaRocks..."
 tar zxpf "$LUAROCKS_TAR" -C /tmp
 
 echo "Building and installing LuaRocks..."
-pushd "$LUAROCKS_DIR" >/dev/null || { echo "Failed to enter $LUAROCKS_DIR"; exit 1; }
+pushd "$LUAROCKS_DIR" >/dev/null || {
+    echo "Failed to enter $LUAROCKS_DIR"
+    exit 1
+}
 ./configure && make && sudo make install
 popd >/dev/null
 
@@ -31,7 +34,10 @@ if [ ! -d "$LUA_SRC" ]; then
 fi
 
 echo "Building Lua 5.1.5 from source in '$LUA_SRC'..."
-pushd "$LUA_SRC" >/dev/null || { echo "Failed to change directory to $LUA_SRC"; exit 1; }
+pushd "$LUA_SRC" >/dev/null || {
+    echo "Failed to change directory to $LUA_SRC"
+    exit 1
+}
 
 if [[ "$(uname)" == "Darwin" ]]; then
     echo "Detected macOS. Running: make macosx"
@@ -46,4 +52,3 @@ sudo make install
 popd >/dev/null
 
 echo "Installation of LuaRocks and Lua 5.1.5 completed successfully."
-
diff --git a/resources/setup b/resources/setup
--- a/resources/setup
+++ b/resources/setup
@@ -32,7 +32,10 @@ else
 fi
 
 # Change into the DEV_ENV directory.
-pushd "$DEV_ENV" >/dev/null || { echo "Failed to change directory to $DEV_ENV" >&2; exit 1; }
+pushd "$DEV_ENV" >/dev/null || {
+    echo "Failed to change directory to $DEV_ENV" >&2
+    exit 1
+}
 
 # Function to run a script in a subshell so that an exit in that script doesn't terminate the main script.
 run_script() {
@@ -54,4 +57,3 @@ run_script "dev-env"
 
 popd >/dev/null
 echo "All scripts executed successfully."
-
diff --git a/runs/dev b/runs/dev
--- a/runs/dev
+++ b/runs/dev
@@ -31,7 +31,10 @@ echo "Extracting LuaRocks..."
 tar zxpf "$LUAROCKS_TAR" -C /tmp
 
 echo "Building and installing LuaRocks..."
-pushd "$LUAROCKS_DIR" >/dev/null || { echo "Failed to enter $LUAROCKS_DIR"; exit 1; }
+pushd "$LUAROCKS_DIR" >/dev/null || {
+    echo "Failed to enter $LUAROCKS_DIR"
+    exit 1
+}
 ./configure && make && sudo make install
 popd >/dev/null
 
@@ -42,4 +45,3 @@ echo "Installing luacheck via LuaRocks..."
 luarocks install luacheck
 
 echo "Installation completed successfully."
-
