Linux: v1

diff --git a/runs/linux/00-install-pacman-yay b/runs/linux/00-install-pacman-yay
--- a/runs/linux/00-install-pacman-yay
+++ b/runs/linux/00-install-pacman-yay
@@ -1,7 +1,43 @@
 #!/usr/bin/env bash
 
-sudo pacman -Syu --needed base-devel git
-if ! command -v yay &> /dev/null; then
-    git clone https://aur.archlinux.org/yay-bin.git /tmp/yay
-    (cd /tmp/yay && makepkg -si --noconfirm)
-fi
+detect_os() {
+    if [ -f /etc/os-release ]; then
+        . /etc/os-release
+        OS=$ID
+    else
+        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
+    fi
+}
+detect_os
+
+install_arch_packages() {
+    if ! command -v yay &>/dev/null; then
+        sudo pacman -S --needed --noconfirm git base-devel
+        git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
+        (cd /tmp/yay-bin && makepkg -si --noconfirm)
+        rm -rf /tmp/yay-bin
+    fi
+}
+
+install_debian_packages() {
+    sudo apt update && sudo apt install -y \
+        build-essential \
+        curl \
+        git \
+        software-properties-common
+}
+
+case $OS in
+arch)
+    install_arch_packages
+    ;;
+ubuntu | debian)
+    install_debian_packages
+    ;;
+*)
+    echo -e "\e[1;31m[ERROR]\e[0m Unsupported OS"
+    exit 1
+    ;;
+esac
+
+echo -e "\e[1;34m[INFO]\e[0m 00-package-manager script completed."
diff --git a/runs/linux/dev b/runs/linux/dev
--- a/runs/linux/dev
+++ b/runs/linux/dev
@@ -3,6 +3,30 @@
 git config --global user.email "huyn.nguyen95@gmail.com"
 git config --global user.name "thenameiswiiwin"
 
-# Lua tools
-yay -S --noconfirm luarocks luajit
-sudo luarocks install luacheck
+detect_os() {
+    if [ -f /etc/os-release ]; then
+        . /etc/os-release
+        OS=$ID
+    else
+        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
+    fi
+}
+detect_os
+
+case $OS in
+arch)
+    yay -S --noconfirm luarocks lua51 wget
+    sudo luarocks install luacheck
+    sudo ln -sf /usr/bin/lua5.1 /usr/local/bin/lua5.1
+    ;;
+ubuntu | debian)
+    sudo apt install -y luarocks wget lua5.1
+    sudo luarocks install luacheck
+    ;;
+*)
+    echo -e "\e[1;31m[ERROR]\e[0m Unsupported OS"
+    exit 1
+    ;;
+esac
+
+echo -e "\e[1;34m[INFO]\e[0m Dev script completed."
